services:
  server:
    build: ./server
    ports:
      - 8001:8001
    env_file: .env
  db:
    image: postgres:14.9
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env

volumes:
  db-data: {}
